fullnameOverride: api-gateway
replicaCount: 1
image:
  repository: studyshop/api-gateway
  tag: "1.0.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  httpPort: 10001
env:
  ORDERS_GRPC_ADDRESS: "static://orders-service:10003"
  INVENTORY_GRPC_ADDRESS: "static://inventory-service:10005"
  NOTIFICATIONS_BASE_URL: "http://notifications-service:10007"
  ORDERS_HEALTH_URL: "http://orders-service:10002/actuator/health"
  INVENTORY_HEALTH_URL: "http://inventory-service:10004/actuator/health"
  PAYMENTS_HEALTH_URL: "http://payments-service:10006/actuator/health"
  NOTIFICATIONS_HEALTH_URL: "http://notifications-service:10007/actuator/health"
  OTEL_SERVICE_NAME: "api-gateway"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_METRICS_EXPORTER: "none"
  OTEL_LOGS_EXPORTER: "none"
resources: {}
