server:
  port: 10002

spring:
  application:
    name: orders-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:10008/orders}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:10009}
    consumer:
      group-id: orders-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

grpc:
  server:
    port: 10003

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.studyshop: INFO
