apiVersion: v1
kind: Service
metadata:
  name: {{ include "orders-service.fullname" . }}
  labels:
    {{- include "orders-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
  selector:
    {{- include "orders-service.selectorLabels" . | nindent 4 }}
